### ISSUE TITLE
No un problema pero una recomendación

### ISSUE THREAD

**Issue by jukeliv** [WhiteHeadbanger/Lunfardo#31]
Capo, si quisieras continuar el lenguaje este, mejorar el interprete y todo eso.

Te full recomiendo este libro, que es [Crafting Interpreters](https://craftinginterpreters.com/) es un libro re completo
y te podria servir para inspirarte, mejorar el lenguaje, cambiar el interprete y cosas así.
Un saludo crack

**Comment by WhiteHeadbanger** [comment]
Gracias, lo voy a leer! El lenguaje lo voy a continuar, aunque actualmente estoy bastante ocupada, tengo un update a medio hacer
